### PR TITLE
Refresh delete and append should update "deleted" and "appended" files in metadata

### LINKED ISSUE #179: RefreshDelete should update appended files list in metadata
### Describe the issue
Currently, when refresh for handling delete case (merged by PR #142 ) fixes index files by removing deleted entries, it updates index signature according to latest source data but does not update `appended` files list.
This can cause correctness issue in a case where source data files have both deleted and appended files, as the index does not fully cover the data (it does not have records from appended files).

This can be fixed by changing `RefreshDelete` class to update index metadata properly by adding appended files (if any) to the `appended` property (under source properties) in index metadata.

**Prerequisite PR:** PR #170 
(PR #170  updates `IndexLogEntry` and adds `appended` property to source properties). 

### To Reproduce
1. User creates an index on some data e.g., "/path/to/dataset/".
2. User deletes some files from the original data and adds some new files under "/path/to/dataset/". 
3. User sets `spark.hyperspace.index.refresh.delete.enabled` flag to `true` and calls refresh to update index by removing entries coming from deleted files.
4. Once refresh finishes successfully, a newer version of index is created and latest metadata shows updated signature and empty `deleted` files (as their records are removed from index). However, currently `appended` files is also set to be empty.

### Expected behavior
Steps 1 to 3 are same as above. 
In step 4, once we check latest index metadata, we should see (new) appended files, which should have been detected during refresh, are added under `appended` property.
  
### Environment 
All.

### PR DESCRIPTION
**Pull request by apoorvedave1**
### What is the context for this pull request?
Refresh Append and Refresh Delete actions should update "appendedFiles" and "deletedFiles" in index metadata. This should happen as below:
**RefreshDeleteAction**
1. it should now pick all the `deletedFiles` from the index metadata as well as look for additional recently deleted files.
2. Once delete operation completes, clear `deletedFiles` from index metadata.
3. Update `appendedFiles` in metadata by adding recently appended files to the `appendedFiles` list.

**RefreshAppendAction**
1. It should now pick all the `appendedFiles` from index metadata as well as look for additional recently appended files.
2. Once append operation completes, clear `appendedFiles` from index metadata.
3. Update `deletedFiles` in metadata by adding recently deleted files to the `deletedFiles` list.

 - **Tracking Issue**: Fixes #179 , #183 
 - **Parent Issue**: Parent PR #162 

### What changes were proposed in this pull request?
bugfixes for #179, #183 

### How was this patch tested?
added unit tests

### CODE REVIEW

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala [hunk 1]
```diff
@@ -76,4 +78,56 @@ private[actions] abstract class RefreshActionBase(
           s"Current index state is ${previousIndexLogEntry.state}")
     }
   }
+
```
Comment (apoorvedave1) [inline src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:81]: Note to reviewers: `def deletedFiles` and `def appendedFiles` were picked directly from `RefreshDeleteAction` and `RefreshAppendAction` respectively.

The only change is, `IndexLogEntry.deletedFiles` is added to the return value of `def deletedFiles`.

In the same way, `IndexLogEntry.appendedFiles` is added to the return value of `def appendedFiles`.

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala [hunk 2]
```diff
@@ -60,25 +59,6 @@ class RefreshAppendAction(
     }
   }
 
-  private lazy val appendedFiles = {
```
Comment (apoorvedave1) [inline src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala:63]: Note for reviewers: this method is moved to RefreshActionBase, and `IndexLogEntry.appendedFiles` is added to the result.

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshDeleteAction.scala [hunk 3]
```diff
@@ -91,36 +89,8 @@ class RefreshDeleteAction(
       indexConfig.indexedColumns)
   }
 
-  /**
-   * Compare list of source data files from previous IndexLogEntry to list
-   * of current source data files, validate fileInfo for existing files and
-   * identify deleted source data files.
-   */
-  private lazy val deletedFiles: Seq[String] = {
```
Comment (apoorvedave1) [inline src/main/scala/com/microsoft/hyperspace/actions/RefreshDeleteAction.scala:99]: Note for reviewers: this method is moved to RefreshActionBase, and `IndexLogEntry.deletedFiles` is added to the result.

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala [hunk 4]
```diff
@@ -76,4 +78,56 @@ private[actions] abstract class RefreshActionBase(
...
+      }
+    }
+
+    delFiles ++ previousIndexLogEntry.deletedFiles
+  }
+
+  protected lazy val appendedFiles = {
+    val relation = previousIndexLogEntry.relations.head
+
+    // TODO: improve this to take last modified time of files into account.
```
Comment (sezruby) [inline src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:118]: Please check: https://github.com/microsoft/hyperspace/pull/187#discussion_r501413876

Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:118]: i actually prefer not to handle this in this pr or merge PR either. Let me create another PR just for this fix.

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala [hunk 5]
```diff
@@ -76,4 +78,56 @@ private[actions] abstract class RefreshActionBase(
...
+          if (!f.equals(v)) {
+            throw HyperspaceException(
+              "Index refresh (to handle deleted source data) aborted. " +
+                s"Existing source data file info is changed (file: ${f.name}).")
+          }
+        case None => delFiles :+= f.name
+      }
+    }
+
+    delFiles ++ previousIndexLogEntry.deletedFiles
```
Comment (sezruby) [inline src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:112]: Do we need to append previously collected deleted files?

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala [hunk 6]
```diff
@@ -108,7 +88,10 @@ class RefreshAppendAction(
     //   https://github.com/microsoft/hyperspace/issues/183
 
     // New entry.
-    entry.copy(content = mergedContent)
+    entry
+      .copy(content = mergedContent)
+      .withNewDeletedFiles(deletedFiles)
```
Comment (sezruby) [inline src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala:93]: It seems we shouldn't allow deletedFiles in `RefreshAppendAction` to handle modified files properly. Please check the below scenario I commented before:

==
Also I think we should consider the following scenario:

- index creation without linage column
- some of source files are modified
- refresh incremental mode:
  - delete => failed, do nothing
  - append => should throw an exception

I think this can be ensured by adding `deletedFiles.isEmpty` condition in `validate` of `RefreshAppendAction`.

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala (hunk 4 above)
Comment (sezruby) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:118]: Then it's ok as long as the fix is included in 0.4.

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala (hunk 6 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala:93]: > refresh incremental mode:
> delete => failed => 

thanks @sezruby , I guess this comment is still applicable only for this PR #187 and not for the current PR, right?
In any case, if delete fails, the application will throw an exception, it will not even go to the next step. `RefreshAppendAction` will not be called at all. So I don't think this assert is necessary in `validate`.

> append => should throw an exception

We never reach this step, previous step will throw an exception before coming here.

Now if you are talking about independently calling `RefreshAppendAction` outside of `refreshIndex(mode = "incremental")`, I still don't think we should add `deleted` check in append validation. It's because in future, we will have `refeshIncremental(mode = "quick")` which will populate the "deleted" in metadata without modifying the index.
If we call `RefreshAppendAction` independently, it should not `throw` if "deleted" is non-empty. It should just update the "deleted" list with additional deleted files and move on.

If you look at `def logEntry`, the "unhandled" deleted files are being added to the "deleted" list at the end of the operation. Does that solve the issue?

File: src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala [hunk 7]
```diff
@@ -397,6 +397,54 @@ case class IndexLogEntry(
     relations.head.data.properties.appendedFiles
   }
 
+  def withAdditionalAppendedFiles(files: Seq[String]): IndexLogEntry = {
```
[the remark this answers is not in the document]
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala]: thanks @sezruby , i realized there was a bug in my log entry api which could have caused some confusion about index metadata. I have fixed it now, please have a look

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala (hunk 5 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:112]: `RefreshDeleteAction` can use this complete collection to handle all deleted files.
`RefreshAppendAction` can use this to update the metadata.
So yes. 

Please correct me if I am wrong.

Comment (imback82) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:112]: So, this is actually a bug fix right (if we had this field populated)?

If so, can you update the comment why we need to add this (e.g., `deletedFiles` is present only if index is not updated to include this info)?

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala [hunk 8]
```diff
@@ -223,6 +221,89 @@ class RefreshIndexTests extends QueryTest with HyperspaceSuite {
     }
   }
 
+  test(
+    "Validate refresh delete action updates appended and deleted files in metadata as" +
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala:225]:
```suggestion
    "Validate refresh delete action updates appended and deleted files in metadata as " +
```

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala [hunk 9]
```diff
@@ -223,6 +221,89 @@ class RefreshIndexTests extends QueryTest with HyperspaceSuite {
...
+      "expected, when some file gets deleted and some appended to source data.") {
+    withSQLConf(
+      IndexConstants.INDEX_LINEAGE_ENABLED -> "true",
+      IndexConstants.REFRESH_DELETE_ENABLED -> "true") {
+      withIndex(indexConfig.indexName) {
+        SampleData.save(
+          spark,
+          nonPartitionedDataPath,
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala:233]: Can we also utilize `withTempPathAsString` here? Eventually, I want to get rid of this predefined dir path if not necessary.

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala [hunk 10]
```diff
@@ -248,4 +329,15 @@ class RefreshIndexTests extends QueryTest with HyperspaceSuite {
 
     fileToDelete
   }
+
+  private def logManager(indexName: String): IndexLogManager = {
+    val indexPath = PathUtils.makeAbsolute(s"$systemPath/$indexName")
+    IndexLogManagerFactoryImpl.create(indexPath)
+  }
+
+  private def fileList(path: String): Seq[String] = {
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala:338]: `listFiles`? I think that's what this `def` does.

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala [hunk 11]
```diff
@@ -223,6 +221,89 @@ class RefreshIndexTests extends QueryTest with HyperspaceSuite {
...
+
+          // Check if refreshed index metadata has "appendedFiles" and "deletedFiles" updated.
+          val entry = logManager(indexConfig.indexName).getLatestStableLog()
+          assert(entry.isDefined)
+          assert(entry.get.isInstanceOf[IndexLogEntry])
+          val indexLogEntry = entry.get.asInstanceOf[IndexLogEntry]
+          assert(indexLogEntry.appendedFiles.isEmpty)
+
+          val newFileList = fileList(testPath).toSet
+          assert(indexLogEntry.deletedFiles.toSet.equals(oldFileList -- newFileList))
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala:301]: `oldFiles -- latestFiles`

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala [hunk 12]
```diff
@@ -223,6 +221,89 @@ class RefreshIndexTests extends QueryTest with HyperspaceSuite {
...
+            .parquet(testPath)
+
+          hyperspace.refreshIndex(indexConfig.indexName)
+
+          // Check if refreshed index metadata has "appendedFiles" and "deletedFiles" updated.
+          val entry = logManager(indexConfig.indexName).getLatestStableLog()
+          assert(entry.isDefined)
+          assert(entry.get.isInstanceOf[IndexLogEntry])
+          val indexLogEntry = entry.get.asInstanceOf[IndexLogEntry]
+          assert(indexLogEntry.appendedFiles.isEmpty)
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala:298]: Can you also assert `latestFiles -- oldFiles` is empty?

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala [hunk 13]
```diff
@@ -223,6 +221,89 @@ class RefreshIndexTests extends QueryTest with HyperspaceSuite {
...
+        SampleData.testData
+          .take(3)
+          .toDF("Date", "RGUID", "Query", "imprs", "clicks")
+          .write
+          .mode("append")
+          .parquet(nonPartitionedDataPath)
+
+        hyperspace.refreshIndex(indexConfig.indexName)
+
+        // Check if refreshed index metadata has "appendedFiles" and "deletedFiles" updated.
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala:254]: Verify that only "appendedFiles" has value because deleted files are "refreshed". Or something like that.

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala (hunk 5 above)
Comment (imback82) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:112]: Also, I guess we cannot add this to the test using the existing APIs due to missing "quick". If so, can you add a TODO so can follow up when we add a "quick" mode?

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala [hunk 14]
```diff
@@ -223,6 +221,89 @@ class RefreshIndexTests extends QueryTest with HyperspaceSuite {
...
+            .mode("append")
+            .parquet(testPath)
+
+          hyperspace.refreshIndex(indexConfig.indexName)
+
+          // Check if refreshed index metadata has "appendedFiles" and "deletedFiles" updated.
+          val entry = logManager(indexConfig.indexName).getLatestStableLog()
+          assert(entry.isDefined)
+          assert(entry.get.isInstanceOf[IndexLogEntry])
+          val indexLogEntry = entry.get.asInstanceOf[IndexLogEntry]
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala:297]: I guess you could also add:
```scala
def getLatestStableLog(indexName: String): IndexLogEntry
```
?

**Review by imback82 — COMMENTED** [review]
generally, looking ok to me

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala (hunk 6 above)
Comment (sezruby) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala]: In my opinion, `quick` mode should be handled with a different action. Yes in general the condition in `validate` is not necessary. But just for double check in case concurrently deleted/modified files and I don't want to let unhandled `deleted files` after `RefreshAppendAction` which may cause some confusion later. How do we handle if there's `deletedFiles` in the latest index log entry? in 0.4 ver? 

BTW, what if a file is modified/appended/deleted in the middle of refresh? Though we don't need to be completely transactional, I think at least we should use the same source file list at the specific point in time and consistent with signature calculation, source content capture and processing appended, deleted files?
WDYT? @apoorvedave1 
cc @imback82

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala (hunk 5 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:116]: thanks, added #195

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala (hunk 6 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala]: Thanks @sezruby , @imback82 . Closing this after offline discussions. As of now, the consensus is on the current behavior of the PR.

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala (hunk 8 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala]: thanks, @imback82 , added

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala (hunk 9 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala]: thanks, @imback82 , added, somehow I forgot it for this test and kept it in the next test. now everything is fixed.

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala (hunk 10 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala]: thanks, @imback82 , fixed

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala (hunk 12 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala:295]: thanks, @imback82 , added

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala (hunk 11 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala]: thanks, @imback82 , fixed

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala (hunk 13 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala]: thanks, @imback82 , fixed

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala (hunk 14 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala]: thanks, @imback82 , added

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala (hunk 1 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:81]: thanks @apoorvedave1 , noted!

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala (hunk 2 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala:63]: thanks @apoorvedave1 , noted!

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshDeleteAction.scala (hunk 3 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshDeleteAction.scala:99]: thanks @apoorvedave1 , noted!

**Review by imback82 — APPROVED** [review]
LGTM, thanks @apoorvedave1!

I will wait on merging this until @sezruby approves since she had few pending comments.

**Comment by sezruby** [comment]
I commented in other PRs - let's resolve the comments with them. 

Thanks @apoorvedave1 for this work!
