### PR TITLE
Replace printStackTrace with Logging

### LINKED ISSUE #53: Replace printStackTrace with Logging in IndexLogManager class
### Describe the issue
Several functions in [`IndexLogManagerImpl`](https://github.com/microsoft/hyperspace/blob/master/src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala)  are using `printStackTrace()` when hitting an unexpected exception.
Change the implementation such that proper Hyperspace logging is used instead of printing the stack.

### To Reproduce
NA

### Expected behavior
[`IndexLogManagerImpl`](https://github.com/microsoft/hyperspace/blob/master/src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala) should not use `printStackTrace()`.
 
### Environment 
NA

### PR DESCRIPTION
**Pull request by sezruby**
### What changes were proposed in this pull request?

Replacement of printStackTrace with Logging. Fixes #53.

### Why are the changes needed?

printStackTrace() outputs to only stderr

### Does this PR introduce _any_ user-facing change?

Yes

Previous behavior
(a test exception from writeLog())
```
java.lang.Exception: test
        at com.microsoft.hyperspace.index.IndexLogManagerImpl.writeLog(IndexLogManager.scala:143)
        at com.microsoft.hyperspace.actions.Action$class.saveEntry(Action.scala:77)
        at com.microsoft.hyperspace.actions.Action$class.begin(Action.scala:52)
        at com.microsoft.hyperspace.actions.Action$class.run(Action.scala:86)
        at com.microsoft.hyperspace.actions.CreateAction.run(CreateAction.scala:27)
        at com.microsoft.hyperspace.index.IndexCollectionManager.create(IndexCollectionManager.scala:42)
        at com.microsoft.hyperspace.index.CachingIndexCollectionManager.create(CachingIndexCollectionManager.scala:77)
        at com.microsoft.hyperspace.Hyperspace.createIndex(Hyperspace.scala:41)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:40)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:45)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:47)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:49)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:51)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:53)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:55)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:57)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:59)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:61)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:63)
        at $line24.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:65)
        at $line24.$read$$iw$$iw$$iw$$iw.<init>(<console>:67)
        at $line24.$read$$iw$$iw$$iw.<init>(<console>:69)
        at $line24.$read$$iw$$iw.<init>(<console>:71)
        at $line24.$read$$iw.<init>(<console>:73)
        at $line24.$read.<init>(<console>:75)
        at $line24.$read$.<init>(<console>:79)
        at $line24.$read$.<clinit>(<console>)
        at $line24.$eval$.$print$lzycompute(<console>:7)
        at $line24.$eval$.$print(<console>:6)
        at $line24.$eval.$print(<console>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
        at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
        at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
        at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:819)
        at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:691)
        at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:404)
        at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:425)
        at org.apache.spark.repl.SparkILoop$$anonfun$process$1.apply$mcZ$sp(SparkILoop.scala:285)
        at org.apache.spark.repl.SparkILoop.runClosure(SparkILoop.scala:159)
        at org.apache.spark.repl.SparkILoop.process(SparkILoop.scala:182)
        at org.apache.spark.repl.Main$.doMain(Main.scala:78)
        at org.apache.spark.repl.Main$.main(Main.scala:58)
        at org.apache.spark.repl.Main.main(Main.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

```

With fix
```
20/07/14 09:05:01 ERROR IndexLogManagerImpl: 
java.lang.Exception: test
        at com.microsoft.hyperspace.index.IndexLogManagerImpl.writeLog(IndexLogManager.scala:143)
        at com.microsoft.hyperspace.actions.Action$class.saveEntry(Action.scala:77)
        at com.microsoft.hyperspace.actions.Action$class.begin(Action.scala:52)
        at com.microsoft.hyperspace.actions.Action$class.run(Action.scala:86)
<same stack>
```

### How was this patch tested?

with a test exception as above

### CODE REVIEW

File: src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala [hunk 1]
```diff
@@ -115,8 +116,7 @@ class IndexLogManagerImpl(indexPath: Path) extends IndexLogManager {
       FileUtil.copy(fs, pathFromId(id), fs, latestStablePath, false, new Configuration)
     } catch {
       case ex: Exception =>
-        // TODO: replace printStackTrace with Logging.
-        ex.printStackTrace()
+        logError("", ex)
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala:119]: Can we add a message here? (e.g., `s"Failed to create the latest stable log with id = '$id'"`.

File: src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala [hunk 2]
```diff
@@ -130,8 +130,7 @@ class IndexLogManagerImpl(indexPath: Path) extends IndexLogManager {
       }
     } catch {
       case ex: Exception =>
-        // TODO: replace printStackTrace with Logging.
-        ex.printStackTrace()
+        logError("", ex)
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala:133]: ditto

File: src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala [hunk 3]
```diff
@@ -148,8 +147,7 @@ class IndexLogManagerImpl(indexPath: Path) extends IndexLogManager {
         fs.rename(tempPath, pathFromId(id))
       } catch {
         case ex: Exception =>
-          // TODO: replace printStackTrace with Logging.
-          ex.printStackTrace()
+          logError("", ex)
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala:150]: ditto

File: src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala (hunk 1 above)
Comment (sezruby) [reply src/main/scala/com/microsoft/hyperspace/index/IndexLogManager.scala]: Updated. Thanks!
