### PR TITLE
refresh doesn't store file names in metadata fix.

### LINKED ISSUE #143: Refresh index does not add updated list of index files to Content in new index log entry
### Describe the issue
Once an index refresh is done successfully, latest stable log is updated to include latest index content. This should include the latest list of index files; however currently `files[]` in index content is left empty after a refresh. 

### To Reproduce
1. User creates an index and as part of index log entry, hyperspace adds list of created index files:

```
// From latestStable log describing v__=0 (i.e. original index, before refresh)
{
  "name" : "filterIndex",
  "derivedDataset" : {
    ...
  },
  "content" : {
    "root" : "file:/C:/myGit/hyperspace-1/src/test/resources/indexLocation/filterIndex/v__=0",
    "directories" : [ {
      "path" : "",
      "files" : [ {
        "name" : "file:/C:/myGit/hyperspace-1/src/test/resources/indexLocation/filterIndex/v__=0/part-00062-7cc80d7d-8ff7-4005-b4f4-32156318639e_00062.c000.snappy.parquet",
        "size" : 668,
        "modifiedTime" : 1599088090146
      }, {
        "name" : "file:/C:/myGit/hyperspace-1/src/test/resources/indexLocation/filterIndex/v__=0/part-00085-7cc80d7d-8ff7-4005-b4f4-32156318639e_00085.c000.snappy.parquet",
        "size" : 695,
        "modifiedTime" : 1599088090065
      }, {
        "name" : "file:/C:/myGit/hyperspace-1/src/test/resources/indexLocation/filterIndex/v__=0/part-00119-7cc80d7d-8ff7-4005-b4f4-32156318639e_00119.c000.snappy.parquet",
        "size" : 725,
        "modifiedTime" : 1599088090097
      }, {
        "name" : "file:/C:/myGit/hyperspace-1/src/test/resources/indexLocation/filterIndex/v__=0/part-00193-7cc80d7d-8ff7-4005-b4f4-32156318639e_00193.c000.snappy.parquet",
        "size" : 714,
        "modifiedTime" : 1599088090112
      }, {
        "name" : "file:/C:/myGit/hyperspace-1/src/test/resources/indexLocation/filterIndex/v__=0/_SUCCESS",
        "size" : 0,
        "modifiedTime" : 1599088090197
      } ],
      "fingerprint" : {
        "kind" : "NoOp",
        "properties" : { }
      }
    } ]
  },
  "source" : {
  ...
```
  
2. User makes some changes and calls refresh which today does a full rebuild of index. If you check the content of latest stable index log entry, index content's root is updated correctly, however no index files is listed in files.
```
// From latestStable log describing v__=1 (i.e. after refresh)
 {
  "name" : "filterIndex",
  "derivedDataset" : {
    ...
  },
  "content" : {
    "root" : "file:/C:/myGit/hyperspace-1/src/test/resources/indexLocation/filterIndex/v__=1",
    "directories" : [ {
      "path" : "",
      "files" : [ ],
      "fingerprint" : {
        "kind" : "NoOp",
        "properties" : { }
      }
    } ]
  },
  "source" : {
    ...
```

 ### Expected behavior
After successful index refresh, in index log entry `content.files[]` should include list of latest index files. 

### Environment 
All.

### PR DESCRIPTION
**Pull request by apoorvedave1**
Fixes #143 

### What changes were proposed in this pull request?
Fix a recent issue where after refresh, new index files are not logged in metadata.

### Why are the changes needed?
Refresh api doesn't store full paths in metadata since the last fileInfo pr. This is a fix for that.

### How was this patch tested?
unit tests

### CODE REVIEW

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala [hunk 1]
```diff
@@ -60,8 +60,7 @@ class RefreshAction(
     IndexConfig(previousIndexLogEntry.name, ddColumns.indexed, ddColumns.included)
   }
 
-  final override lazy val logEntry: LogEntry =
-    getIndexLogEntry(spark, df, indexConfig, indexDataPath)
+  final override def logEntry: LogEntry = getIndexLogEntry(spark, df, indexConfig, indexDataPath)
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala:63]: Shall we add a test? Any regression/bug fix should come with a test.

Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala:62]: thanks, @imback82 , added.

File: src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala [hunk 2]
```diff
@@ -228,14 +227,26 @@ class IndexManagerTests extends HyperspaceSuite with SQLHelper {
...
 
+        // Check if lastest log file is updated with newly created index files
+        val indexPath = PathUtils.makeAbsolute(newIndexLocation)
+        val logManager = IndexLogManagerFactoryImpl.create(indexPath)
+        val latestLog = logManager.getLatestLog()
+        assert(latestLog.isDefined && latestLog.get.isInstanceOf[IndexLogEntry])
+        val indexLog = latestLog.get.asInstanceOf[IndexLogEntry]
+        assert(indexLog.content.directories.nonEmpty)
+        assert(indexLog.content.directories.head.files.nonEmpty)
+        // TODO: change the below condition from `exists` to `forall` when _SUCCESS is removed.
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala:247]: I guess we can just do `forall(f => f.name.startsWith("_") || f.name.contains("part-000")))`, so that when `_SUCCESS` is removed, this test would fail.

File: src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala [hunk 3]
```diff
@@ -228,14 +227,26 @@ class IndexManagerTests extends HyperspaceSuite with SQLHelper {
...
 
         // Check if index got updated
         assert(indexCount == 3)
 
+        // Check if lastest log file is updated with newly created index files
+        val indexPath = PathUtils.makeAbsolute(newIndexLocation)
+        val logManager = IndexLogManagerFactoryImpl.create(indexPath)
+        val latestLog = logManager.getLatestLog()
+        assert(latestLog.isDefined && latestLog.get.isInstanceOf[IndexLogEntry])
+        val indexLog = latestLog.get.asInstanceOf[IndexLogEntry]
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala:244]: can we check the state is `ACTIVE`?

**Review by imback82 — APPROVED** [review]
LGTM except for few minor comments. Thanks @apoorvedave1!

**Review by sezruby — DISMISSED** [review]
LGTM Thanks!

**Comment by pirz** [comment]
LGTM, Thanks @apoorvedave1 for a quick fix PR.

File: src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala (hunk 3 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala:244]: thanks @imback82 , added

File: src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala (hunk 2 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala]: thanks @imback82 , added with slight modification. `startsWith(_)` ->`contains(_SUCCESS)` because currently f.name is full path

**Comment by imback82** [comment]
@apoorvedave1 can you fix the build? https://dev.azure.com/ossspark/public/_build/results?buildId=514&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=f3c91641-114c-5821-bd1e-444cf5c75ddb

**Comment by apoorvedave1** [comment]
> @apoorvedave1 can you fix the build? https://dev.azure.com/ossspark/public/_build/results?buildId=514&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=f3c91641-114c-5821-bd1e-444cf5c75ddb

this seems like an old build. the latest build on the latest commit hasn't run yet. Could you please tell me how to start the build?

**Comment by imback82** [comment]
I pushed an empty commit to retrigger: `git commit --allow-empty -m "Trigger Build"`

**Comment by apoorvedave1** [comment]
> I pushed an empty commit to retrigger: `git commit --allow-empty -m "Trigger Build"`

😆 I did the same.

**Comment by imback82** [comment]
Previous test succeeded, so I am merging this.
