### PR TITLE
Merge append and delete actions on indexes on modified source data

### LINKED ISSUE #179: RefreshDelete should update appended files list in metadata
### Describe the issue
Currently, when refresh for handling delete case (merged by PR #142 ) fixes index files by removing deleted entries, it updates index signature according to latest source data but does not update `appended` files list.
This can cause correctness issue in a case where source data files have both deleted and appended files, as the index does not fully cover the data (it does not have records from appended files).

This can be fixed by changing `RefreshDelete` class to update index metadata properly by adding appended files (if any) to the `appended` property (under source properties) in index metadata.

**Prerequisite PR:** PR #170 
(PR #170  updates `IndexLogEntry` and adds `appended` property to source properties). 

### To Reproduce
1. User creates an index on some data e.g., "/path/to/dataset/".
2. User deletes some files from the original data and adds some new files under "/path/to/dataset/". 
3. User sets `spark.hyperspace.index.refresh.delete.enabled` flag to `true` and calls refresh to update index by removing entries coming from deleted files.
4. Once refresh finishes successfully, a newer version of index is created and latest metadata shows updated signature and empty `deleted` files (as their records are removed from index). However, currently `appended` files is also set to be empty.

### Expected behavior
Steps 1 to 3 are same as above. 
In step 4, once we check latest index metadata, we should see (new) appended files, which should have been detected during refresh, are added under `appended` property.
  
### Environment 
All.

### PR DESCRIPTION
**Pull request by apoorvedave1**
NOTES TO REVIEWERS:
1. Index metadata changes from another PR #170 by @pirz have been handpicked without which correctness cannot be guaranteed for this PR.
Changes include:
  - 1. add "appended" list to index metadata
  - 2. add "deleted" list to index metadata
Reviewers are NOT required to review PR #170 to review this PR.

### What is the context for this pull request?
Hyperspace currently handles append support and delete support on modifiable source data separately. Users can either allow deletion of some source files and refresh their index, or they can allow adding files to data and refresh the index.

This PR merges these operations which will enable users to have a fully modifyable data source. Users can delete some of the indexed source files and also append some new source files. A `refreshIndex(indexName, mode = "incremental")` operation will allow users to update their indexes to accommodate for all these changes.

 - **Tracking Issue**: #149 , also Fixes #179, #183
 - **Parent Issue**: #136
 - **Dependencies**: NA

#### 1
Merge the behavior of `RefreshDeleteAction` and `RefreshAppendAction` in a single user facing api `refreshIndex(indexName, mode = "incremental")`. When the user calls this api, hyperspace should update the index by removing records from all the deleted source files, and adding records from the newly added source files.

#### 2 PR #188 MERGED
IndexLogEntry will support storing "appended" and "deleted" files (these changes were picked from #170 for correctness). 

#### 3 PR #191 MERGED
Update RefreshDeleteAction and RefreshAppendAction to also update the "appended" and "deleted" files list in index metadata.

#### 4 PR #189 MERGED
If no updates to data source are found, it will NOT throw an exception anymore. This means:
- If no deleted files are found, log a warning message and exit the RefreshDeleteAction without throwing exception.
- If no appended files are found, log a warning message and exit the RefreshAppendAction without throwing exception.

#### 5 PR #194 MERGED
Bug fix: if 'appended' or 'deleted' files are present in index metadata and hybrid scan is disabled, do NOT use those indexes. Otherwise this will lead to incorrect results.

### Does this PR introduce _any_ user-facing change?
Yes.
- This PR introduces `refreshIndex(indexName, mode = "incremental")` for the users. Users can choose this over `mode="full"` for a faster refresh of index files.
- index metadata files now contain "appended" and "deleted" list of files from original source data. These files are those for which index has not been updated.

### How was this patch tested?
added unit tests where we delete some files from original indexed data, followed by appending new data to original data. A `refresh(indexName, mode = "incremental")` will update the indexes such that newly created index files will reflect the most recent version of the data.

### CODE REVIEW

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala [hunk 1]
```diff
@@ -76,4 +78,56 @@ private[actions] abstract class RefreshActionBase(
...
+
+    delFiles ++ previousIndexLogEntry.deletedFiles
+  }
+
+  protected lazy val appendedFiles = {
+    val relation = previousIndexLogEntry.relations.head
+
+    // TODO: improve this to take last modified time of files into account.
+    //   https://github.com/microsoft/hyperspace/issues/182
+    val originalFiles = relation.data.properties.content.files.map(_.toString)
```
Comment (sezruby) [inline src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:120]: Can we handle this issue with this PR?
It might cause some correctness issue:
- modified files are handled as deleted => delete the index rows
- not handled as appended => missing data

Also I think we should consider the following scenario:
- index creation without linage column
- some of source files are modified
- refresh incremental mode:
  - delete => failed, do nothing
  - append => should throw an exception

File: src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala [hunk 2]
```diff
@@ -63,13 +64,12 @@ class IndexCollectionManager(
...
   }
 
-  override def refresh(indexName: String): Unit = {
+  override def refresh(indexName: String, mode: String = REFRESH_MODE_INCREMENTAL): Unit = {
     withLogManager(indexName) { logManager =>
       val indexPath = PathResolver(spark.sessionState.conf).getIndexPath(indexName)
       val dataManager = indexDataManagerFactory.create(indexPath)
-      if (HyperspaceConf.refreshDeleteEnabled(spark)) {
+      if (mode.equals(REFRESH_MODE_INCREMENTAL)) {
         new RefreshDeleteAction(spark, logManager, dataManager).run()
```
Comment (sezruby) [inline src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala:72]: I think we barely need to merge these two actions as `RefreshAppendAction` only handles newly appended files - no duplicate index data write.

+ BTW it might be good to log the number(and size) of appended files & deleted files in info level?

**Comment by sezruby** [comment]
Need to be consistent the lineage column config of each index entry when RefreshAppendAction - 
https://github.com/microsoft/hyperspace/blob/1d3ac492b0445e2c64aa8798945ea29d9e8b4cd9/src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala#L171

File: src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala (hunk 2 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala:72]: > I think we barely need to merge these two actions as `RefreshAppendAction` only handles newly appended files - no duplicate index data write.

sorry i didn't understand what you mean by this. Are you saying what I am doing is correct?

Comment (sezruby) [reply src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala:72]: Yes, means this approach looks fine. I just wanted to correct myself :)

Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala:72]: Sure thanks for confirming! I will add the log lines as well. thanks!

**Comment by apoorvedave1** [comment]
> Need to be consistent the lineage column config of each index entry when RefreshAppendAction -
> https://github.com/microsoft/hyperspace/blob/1d3ac492b0445e2c64aa8798945ea29d9e8b4cd9/src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala#L171

oh nice catch :) ! thanks!

**Comment by sezruby** [comment]
> 2 PR #188 MERGED
IndexLogEntry will support storing "appended" and "deleted" files (these changes were picked from #170 for correctness).
>
> 3
Update RefreshDeleteAction and RefreshAppendAction to also update the "appended" and "deleted" files list in index metadata.

Just for clarification: this is for `quick` refresh, but I think we could utilize this for `RefreshDeleteAction` - in case RefreshAppendAction failed.
- There are deleted and appended files
- RefreshDeleteAction => success / `deletedFiles` should be empty, `appendedFiles` should contain the list of appended files.
- RefreshAppendAction
  - fail => non empty `appendedFile` should be handled properly in query time => hybrid scan
  - success => `appendedFiles` should be cleared.

After processing the appended/deleted source files, we should clear the lists.

**Comment by apoorvedave1** [comment]
> > 2 PR #188 MERGED
> > IndexLogEntry will support storing "appended" and "deleted" files (these changes were picked from #170 for correctness).
> > 3
> > Update RefreshDeleteAction and RefreshAppendAction to also update the "appended" and "deleted" files list in index metadata.
> 
> Just for clarification: this is for `quick` refresh, but I think we could utilize this for `RefreshDeleteAction` - in case RefreshAppendAction failed.
> 
> * There are deleted and appended files
> * RefreshDeleteAction => success / `deletedFiles` should be empty, `appendedFiles` should contain the list of appended files.
> * RefreshAppendAction
>   
>   * fail => non empty `appendedFile` should be handled properly in query time => hybrid scan
>   * success => `appendedFiles` should be cleared.
> 
> After processing the appended/deleted source files, we should clear the lists.

Thanks @sezruby , could you please check `RefreshActionBase, RefreshAppendAction, RefreshIncrmentalAction`, I think I am handling everything you mentioned here for refresh mode "incremental" as well, unless I missed any specific case, i think these changes are part of this PR.
Please Refer `def logEntry`, `def appendedFiles`, `def deletedFiles` in these classes.

Please let me konw if I missed any case.

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala (hunk 1 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshActionBase.scala:120]: thanks @sezruby , I actually prefer not to handle #182 in this PR.
we know it's a correctness bug if user replaces a data file with another file with exact same name, but I think that will be solved when we handle #182 (soon).

I will keep this issue open for the other scenario you pointed out.

**Comment by sezruby** [comment]
> > Need to be consistent the lineage column config of each index entry when RefreshAppendAction -
> > https://github.com/microsoft/hyperspace/blob/1d3ac492b0445e2c64aa8798945ea29d9e8b4cd9/src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala#L171
> 
> oh nice catch :) ! thanks!

Just to be sure, bucket number also should be consistent with the previous log entry:
https://github.com/microsoft/hyperspace/blob/1d3ac492b0445e2c64aa8798945ea29d9e8b4cd9/src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala#L121

File: src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala [hunk 3]
```diff
@@ -252,40 +252,6 @@ class IndexManagerTests extends HyperspaceSuite with SQLHelper {
     }
   }
 
-  test("Verify refresh-incremental (append-only) is a no-op if no new files found.") {
```
Comment (apoorvedave1) [inline src/test/scala/com/microsoft/hyperspace/index/IndexManagerTests.scala:255]: there is another test which does exactly this in `RefreshIndexTests` so this is not required anymore. This happened after merging append and delete within refresh.

File: src/main/scala/com/microsoft/hyperspace/Hyperspace.scala [hunk 4]
```diff
@@ -73,8 +74,8 @@ class Hyperspace(spark: SparkSession) {
    *
    * @param indexName Name of the index to refresh.
    */
-  def refreshIndex(indexName: String): Unit = {
-    indexManager.refresh(indexName)
+  def refreshIndex(indexName: String, mode: String = REFRESH_MODE_INCREMENTAL): Unit = {
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/Hyperspace.scala:77]:
```scala
def refreshIndex(indexName: String): Unit = {
  refreshIndex(indexName, REFRESH_MODE_INCREMENTAL)
}

// Comment which modes are supported.
def refreshIndex(indexName: String, mode: String): Unit = {
  indexManager.refresh(indexName, mode)
}

```

File: src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala [hunk 5]
```diff
@@ -92,9 +94,9 @@ class CachingIndexCollectionManager(
     super.vacuum(indexName)
   }
 
-  override def refresh(indexName: String): Unit = {
+  override def refresh(indexName: String, mode: String = REFRESH_MODE_INCREMENTAL): Unit = {
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala:97]: let's remove default at this level.

File: src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala [hunk 6]
```diff
@@ -63,13 +63,12 @@ class IndexCollectionManager(
     }
   }
 
-  override def refresh(indexName: String): Unit = {
+  override def refresh(indexName: String, mode: String = REFRESH_MODE_INCREMENTAL): Unit = {
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala:66]: ditto

File: src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala (hunk 5 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala]: thanks @imback82 , removed

File: src/main/scala/com/microsoft/hyperspace/Hyperspace.scala (hunk 4 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/Hyperspace.scala]: thanks @imback82 , updated

File: src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala (hunk 6 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala]: thanks @imback82 , removed

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala [hunk 7]
```diff
@@ -265,38 +264,86 @@ class RefreshIndexTests extends QueryTest with HyperspaceSuite {
...
+    }
+  }
 
-          // Verify "appendedFiles" is cleared and "deletedFiles" is updated after refresh.
-          val indexLogEntry = getLatestStableLog(indexConfig.indexName)
-          assert(indexLogEntry.appendedFiles.isEmpty)
+  test(
+    "Validate incremental refresh index when some file gets deleted and some appended to " +
+      "source data.") {
+    withSQLConf(IndexConstants.INDEX_LINEAGE_ENABLED -> "true") {
```
Comment (apoorvedave1) [inline src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala:309]: use `withTempDirAsString` for this test

File: src/main/scala/com/microsoft/hyperspace/Hyperspace.scala [hunk 8]
```diff
@@ -74,7 +75,18 @@ class Hyperspace(spark: SparkSession) {
    * @param indexName Name of the index to refresh.
    */
   def refreshIndex(indexName: String): Unit = {
-    indexManager.refresh(indexName)
+    refreshIndex(indexName, REFRESH_MODE_FULL)
+  }
+
+  /**
+   * Update indexes for the latest version of the data. This api provides a few
```
Comment (sezruby) [inline src/main/scala/com/microsoft/hyperspace/Hyperspace.scala:82]: a few ..?

File: src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala [hunk 9]
```diff
@@ -409,76 +410,74 @@ class E2EHyperspaceRulesTests extends HyperspaceSuite with SQLHelper {
...
-
-        // With Hyperspace enabled, verify bucketing works as expected. This is reflected in
-        // shuffle nodes being eliminated.
-        spark.enableHyperspace()
-        val dfWithHyperspaceEnabled = query()
-        shuffleNodes = dfWithHyperspaceEnabled.queryExecution.executedPlan.collect {
-          case s: ShuffleExchangeExec => s
-        }
-        assert(shuffleNodes.isEmpty)
+      // Append to original data.
```
Comment (sezruby) [inline src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala:428]: Could you also test with deleted files?
and also could you add some e2e tests using refreshed index? and compare the actual query results w/ or w/o index?

**Review by sezruby — COMMENTED** [review]
Please don't forget to handle this in 0.4: https://github.com/microsoft/hyperspace/pull/187#issuecomment-706009905

**Comment by apoorvedave1** [comment]
> Please don't forget to handle this in 0.4: [#187 (comment)](https://github.com/microsoft/hyperspace/pull/187#issuecomment-706009905)

Thanks for the reminders. I prefer not to take this in this PR

**Comment by apoorvedave1** [comment]
> > Please don't forget to handle this in 0.4: [#187 (comment)](https://github.com/microsoft/hyperspace/pull/187#issuecomment-706009905)
> 
> Thanks for the reminders. I prefer not to take this in this PR

Could you please create an issue?

File: src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala (hunk 9 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala:428]: thanks @sezruby , please check this existing test https://github.com/microsoft/hyperspace/blob/master/src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala#L493

File: src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala [hunk 10]
```diff
@@ -409,76 +409,74 @@ class E2EHyperspaceRulesTests extends HyperspaceSuite with SQLHelper {
       sortedRowsWithHyperspaceDisabled.sameElements(getSortedRows(dfAfterHyperspaceDisabled)))
   }
 
-  test("Verify Join Index Rule utilizes indexes correctly after incremental refresh.") {
+  test("Verify JoinIndexRule utilizes indexes correctly after incremental refresh (append-only).") {
```
Comment (apoorvedave1) [inline src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala:412]: NOTE: this is a preexsisting test with only a REFRESH_APPEND_ENABLED flag removed

File: src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala (hunk 7 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/RefreshIndexTests.scala]: thanks @apoorvedave1 :D done!

File: src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala (hunk 9 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala:427]: added test to verify data

File: src/main/scala/com/microsoft/hyperspace/Hyperspace.scala [hunk 11]
```diff
@@ -74,7 +75,19 @@ class Hyperspace(spark: SparkSession) {
...
+    refreshIndex(indexName, REFRESH_MODE_FULL)
+  }
+
+  /**
+   * Update indexes for the latest version of the data. This api provides a few supported
+   * refresh modes as listed below.
+   *
+   * @param indexName Name of the index to refresh.
+   * @param mode Refresh mode. Currently supported modes are [[REFRESH_MODE_INCREMENTAL]] and
+   *             [[REFRESH_MODE_FULL]]
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/Hyperspace.scala:87]: Can we not use constants at this level similar to https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/Dataset.scala#L997. Other languages will not be able to utilize it anyway, and we can just use them internally.

File: src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala [hunk 12]
```diff
@@ -63,16 +63,17 @@ class IndexCollectionManager(
     }
   }
 
-  override def refresh(indexName: String): Unit = {
+  override def refresh(indexName: String, mode: String): Unit = {
     withLogManager(indexName) { logManager =>
       val indexPath = PathResolver(spark.sessionState.conf).getIndexPath(indexName)
       val dataManager = indexDataManagerFactory.create(indexPath)
-      if (HyperspaceConf.refreshDeleteEnabled(spark)) {
+      if (mode.equals(REFRESH_MODE_INCREMENTAL)) {
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala:70]: Can we allow case insensitive comparison?

**Comment by imback82** [comment]
Can you or @thrajput also update the Python binding?

@AFFogarty can help on the C# side once 0.3 is released. (I will ping you @AFFogarty 😄 when it's ready)

File: src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala (hunk 12 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala]: thanks @imback82 , added

File: src/main/scala/com/microsoft/hyperspace/Hyperspace.scala (hunk 11 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/Hyperspace.scala]: thanks @imback82 , added

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala [hunk 13]
```diff
@@ -37,9 +37,9 @@ class RefreshAction(
     extends RefreshActionBase(spark, logManager, dataManager) {
 
   final override def op(): Unit = {
-    // TODO: The current implementation picks the number of buckets from session config.
-    //   This should be user-configurable to allow maintain the existing bucket numbers
-    //   in the index log entry.
+    // TODO: The current implementation picks the number of buckets INDEX_LINEAGE_ENABLED from
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala:40]: What is INDEX_LINEAGE_ENABLED here?

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala [hunk 14]
```diff
@@ -41,9 +41,9 @@ class RefreshAppendAction(
     dataManager: IndexDataManager)
     extends RefreshActionBase(spark, logManager, dataManager) {
   final override def op(): Unit = {
-    // TODO: The current implementation picks the number of buckets from session config.
-    //   This should be user-configurable to allow maintain the existing bucket numbers
-    //   in the index log entry.
+    // TODO: The current implementation picks the number of buckets INDEX_LINEAGE_ENABLED from
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala:44]: ditto

File: src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala [hunk 15]
```diff
@@ -18,6 +18,8 @@ package com.microsoft.hyperspace.index
 
 import org.apache.spark.sql.{DataFrame, SparkSession}
 
+import com.microsoft.hyperspace.index.IndexConstants.REFRESH_MODE_INCREMENTAL
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala:21]: remove?

File: src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala [hunk 16]
```diff
@@ -63,16 +63,17 @@ class IndexCollectionManager(
...
-      if (HyperspaceConf.refreshDeleteEnabled(spark)) {
+      if (mode.equalsIgnoreCase(REFRESH_MODE_INCREMENTAL)) {
         new RefreshDeleteAction(spark, logManager, dataManager).run()
-      } else if (HyperspaceConf.refreshAppendEnabled(spark)) {
         new RefreshAppendAction(spark, logManager, dataManager).run()
-      } else {
+      } else if (mode.equalsIgnoreCase(REFRESH_MODE_FULL)) {
         new RefreshAction(spark, logManager, dataManager).run()
+      } else {
+        throw HyperspaceException(s"Unsupported refresh mode $mode found.")
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/IndexCollectionManager.scala:76]:
```suggestion
        throw HyperspaceException(s"Unsupported refresh mode '$mode' found.")
```

File: src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala [hunk 17]
```diff
@@ -532,14 +527,80 @@ class E2EHyperspaceRulesTests extends HyperspaceSuite with SQLHelper {
...
+        // Verify correctness of results.
+        spark.disableHyperspace()
+        val dfWithHyperspaceDisabled = query()
+        spark.enableHyperspace()
+        val dfWithHyperspaceEnabled = query()
+        checkAnswer(dfWithHyperspaceDisabled, dfWithHyperspaceEnabled)
+      }
+    }
+  }
+
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala:603]: Should we also check the behavior when the lineage is off, but refresh incremental is called?

File: src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala [hunk 18]
```diff
@@ -532,14 +527,80 @@ class E2EHyperspaceRulesTests extends HyperspaceSuite with SQLHelper {
...
+        // Delete some source data file.
+        val dataPath = new Path(testPath, "*parquet")
+        val dataFileNames = dataPath
+          .getFileSystem(new Configuration)
+          .globStatus(dataPath)
+          .map(_.getPath)
+
+        assert(dataFileNames.nonEmpty)
+        val fileToDelete = dataFileNames.head
+        FileUtils.delete(fileToDelete)
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala:565]: Can you create a helper function and use it across tests (I see this logic is duplicated)? Something like:
```scala
// Returns the paths of deleted files.
def deleteFiles(path: String, pattern: String, numFilesToDelete: Int): Seq[Path]
```

File: src/test/scala/com/microsoft/hyperspace/index/IndexCollectionManagerTest.scala [hunk 19]
```diff
@@ -134,6 +135,6 @@ class IndexCollectionManagerTest extends SparkFunSuite with SparkInvolvedSuite {
 
   test("refresh() throws exception if index is not found") {
     when(mockFileSystem.exists(new Path(indexSystemPath, "idx4"))).thenReturn(false)
-    intercept[HyperspaceException](indexCollectionManager.refresh("idx4"))
+    intercept[HyperspaceException](indexCollectionManager.refresh("idx4", REFRESH_MODE_FULL))
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/IndexCollectionManagerTest.scala:138]: What's the expected behavior for incremental?

Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/IndexCollectionManagerTest.scala:137]: thanks @imback82 , added test

File: src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala (hunk 18 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala]: thanks @imback82 , added

File: src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala (hunk 15 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/index/CachingIndexCollectionManager.scala]: thansk @imback82 , removed

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala (hunk 14 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshAppendAction.scala]: ditto

File: src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala (hunk 13 above)
Comment (apoorvedave1) [reply src/main/scala/com/microsoft/hyperspace/actions/RefreshAction.scala]: thanks @imback82 , cleaned up this message

File: src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala (hunk 17 above)
Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala:589]: Thanks @imback82, 
This test exists:
1. lineage is off, delete some files, call refresh incremental => fails

Are you suggesting a test with above scenario with some appended files as well?

Comment (imback82) [reply src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala:589]: no, I think the existing test should be OK.

Comment (apoorvedave1) [reply src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTests.scala:589]: cool thanks.

**Review by imback82 — APPROVED** [review]
LGTM, thanks @apoorvedave1!

I will wait others to approve as well before merging.

**Comment by imback82** [comment]
Merging this as no responses from @sezruby and @pirz. Feel free to make comments if you have any.
