### PR TITLE
Deduplicate getIndexesForPlan and findCoveringIndexes

### LINKED ISSUE #51: Deduplicate getIndexesForPlan() and findCoveringIndexes() functions which are duplicated in FilterIndexRule and JoinIndexRule
### Describe the issue
`FilterIndexRule.findCoveringIndexes()` function and `JoinIndexRule.getIndexesForPlan()` function are similar in  implementation.
Refactor them as common code in a single function and change the classes to use that.

### To Reproduce
NA

### Expected behavior
FilterIndex rule and JoinIndex rule implementation under [rules](https://github.com/microsoft/hyperspace/tree/master/src/main/scala/com/microsoft/hyperspace/index/rules) should not have duplicate code for finding covering indexes.

### Environment 
NA

### PR DESCRIPTION
**Pull request by sezruby**
### What changes were proposed in this pull request?

Fixes #51 
Deduplicate getIndexesForPlan and findCoveringIndexes functions

### Why are the changes needed?

code duplication

### Does this PR introduce _any_ user-facing change?

No

### How was this patch tested?

sbt test
JoinIndexRuleTest & FilterIndexRuleTest

### CODE REVIEW

**Comment by sezruby** [comment]
Hi reviewers! Please just let me know **any** kind of issues such as style, naming, location and etc. as I'm new to Scala :)
TIA!

**Comment by rapoth** [comment]
Thank you! The [coding guide](https://github.com/microsoft/hyperspace/blob/master/docs/coding-guidelines/scala-coding-style.md) might be of help.

File: src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala [hunk 1]
```diff
@@ -35,4 +42,35 @@ object LogicalPlanUtils {
       case _ => false
     }
   }
+
+  def getAllAvailableIndexes(states: Seq[String] = Seq()): Seq[IndexLogEntry] = {
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala:46]: Let's not expose this API since it has a tight dependency on spark session, context, etc.

File: src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala [hunk 2]
```diff
@@ -35,4 +42,35 @@ object LogicalPlanUtils {
...
+    Hyperspace
+      .getContext(SparkSession.getActiveSession.get)
+      .indexCollectionManager
+      .getIndexes(states)
+  }
+
+  def getCandidateIndexesForPlan(plan: LogicalPlan): Seq[IndexLogEntry] = {
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala:53]: Can we update this to
```scala
/**
 * Can we add a brief description of what this function does?
 */
def getCandidateIndexes(indexManager: IndexManager, plan: LogicalPlan): Seq[IndexLogEntry]
```
? The caller will still have to get active spark session, etc., which is fine.

File: src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala [hunk 3]
```diff
@@ -35,4 +42,35 @@ object LogicalPlanUtils {
...
+    val signatureMap: mutable.Map[String, String] = mutable.Map()
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala:54]: Let's retain the existing comment (reworded a bit) and remove type for a local variable:
```scala
// Map of a signature provider to a signature generated for the given plan.
val signatureMap = mutable.Map[String, String]()
```

File: src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala (hunk 2 above)
Comment (imback82) [reply src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala:53]: I also feel that this function should belong to rules (at least for now). Can we create `RuleUtils.scala` under `com.microsoft.hyperspace.index.rules`?

And let's also add a test suite for that.

File: src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala [hunk 4]
```diff
@@ -148,43 +144,16 @@ object FilterIndexRule extends Rule[LogicalPlan] with Logging {
       projectColumns: Seq[String],
       filterColumns: Seq[String],
       fsRelation: HadoopFsRelation): Seq[IndexLogEntry] = {
+    val cIndexes = LogicalPlanUtils.getCandidateIndexesForPlan(project)
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/rules/FilterIndexRule.scala:147]: nit: `val candidateIndexes`?

File: src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala (hunk 2 above)
Comment (sezruby) [reply src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala:53]: Ok, but it seems that common test code refactoring is required for Rules tests. (according to the comment in FilterIndexRuleTest 😊)
So how about filing a new issue for the refactoring and let this change be tested with the current tests?

Comment (imback82) [reply src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala]: Rule tests refactoring is different from this. Also, I think this is a good ramp-up work for you anyway.

File: src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+
+object RuleUtils {
+
+  /**
+   * Get ACTIVE indexes for this logical plan.
+   *
+   * @param plan logical plan
+   * @return indexes built for this plan
+   */
+  def getCandidateIndexesForPlan(plan: LogicalPlan): Seq[IndexLogEntry] = {
```
[the remark this answers is not in the document]
Comment (sezruby) [reply src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala:36]: Sorry I overlooked the comment. Did you mean IndexCollectionManager? or IndexManager indeed?

File: src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala [hunk 6]
```diff
@@ -0,0 +1,68 @@
...
+import org.apache.spark.sql.catalyst.plans.logical.LogicalPlan
+
+import com.microsoft.hyperspace.Hyperspace
+import com.microsoft.hyperspace.actions.Constants
+import com.microsoft.hyperspace.index.{IndexLogEntry, LogicalPlanSignatureProvider}
+
+object RuleUtils {
+
+  /**
+   * Get ACTIVE indexes for this logical plan.
```
[the remark this answers is not in the document]
Comment (sezruby) [reply src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala:31]: Fixed, thanks!

File: src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala (hunk 5 above)
[the remark this answers is not in the document]
Comment (imback82) [reply src/main/scala/com/microsoft/hyperspace/index/rules/RuleUtils.scala:36]: Yea, I meant `trait IndexManager`

File: src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala (hunk 2 above)
Comment (sezruby) [reply src/main/scala/com/microsoft/hyperspace/util/LogicalPlanUtils.scala]: I added RuleUtilsTest and revised the tests under rules a bit. Thanks!

File: src/test/scala/com/microsoft/hyperspace/index/rules/RuleTestHelper.scala [hunk 7]
```diff
@@ -16,10 +16,17 @@
...
+import org.apache.spark.sql.execution.datasources.{FileIndex, HadoopFsRelation, LogicalRelation}
+import org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat
+import org.apache.spark.sql.types.{StructField, StructType}
 
-import com.microsoft.hyperspace.index.LogicalPlanSignatureProvider
+import com.microsoft.hyperspace.actions.Constants
+import com.microsoft.hyperspace.index.{Content, CoveringIndex, Hdfs, IndexConstants, IndexLogEntry, IndexLogManagerImpl, LogicalPlanFingerprint, LogicalPlanSignatureProvider, NoOpFingerprint, Signature, Source, SparkPlan}
+import com.microsoft.hyperspace.index.serde.LogicalPlanSerDeUtils
 
 object RuleTestHelper {
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/rules/RuleTestHelper.scala:31]: Thanks for refactoring these as well.

Can we change this to `trait RuleTestUtils` simliar to [SQLTestUtils](https://github.com/apache/spark/blob/master/sql/core/src/test/scala/org/apache/spark/sql/test/SQLTestUtils.scala) so that you can do `class JoinIndexRuleTest extends HyperspaceSuite with RuleTestUtils`? (and now you can omit `RuleTestHelper.` for most cases).

File: src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala [hunk 8]
```diff
@@ -0,0 +1,123 @@
...
+    spark.conf.set(IndexConstants.INDEX_SYSTEM_PATH, systemPath.toUri.toString)
+    clearCache()
+  }
+
+  test("Verify indexes are matched by signature correctly.") {
+    val indexManager = Hyperspace
+      .getContext(SparkSession.getActiveSession.get)
+      .indexCollectionManager
+
+    val indexPlan = Project(Seq(t1c1, t1c2, t1c3), t1ProjectNode)
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala:108]: nit: How about:
```Scala
    val plan1 = Project(Seq(t1c1, t1c2, t1c3), t1ProjectNode)
    assert(RuleUtils.getCandidateIndexes(indexManager, plan1).length == 3)

    val plan2 = Project(Seq(t2c1, t2c4), t2ProjectNode)
    assert(RuleUtils.getCandidateIndexes(indexManager, plan2).length == 2)

    // Delete an index for plan1.
    indexManager.delete("t1i1")
    assert(RuleUtils.getCandidateIndexes(indexManager, plan1).length == 2)
```
?

File: src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala [hunk 9]
```diff
@@ -0,0 +1,123 @@
...
+
+  before {
+    spark.conf.set(IndexConstants.INDEX_SYSTEM_PATH, systemPath.toUri.toString)
+    clearCache()
+  }
+
+  test("Verify indexes are matched by signature correctly.") {
+    val indexManager = Hyperspace
+      .getContext(SparkSession.getActiveSession.get)
+      .indexCollectionManager
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala:106]: nit: `val indexManager = IndexCollectionManager(spark)`

File: src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala [hunk 10]
```diff
@@ -0,0 +1,123 @@
...
+  }
+
+  override def afterAll(): Unit = {
+    FileUtils.delete(parentPath)
+    super.afterAll()
+  }
+
+  before {
+    spark.conf.set(IndexConstants.INDEX_SYSTEM_PATH, systemPath.toUri.toString)
+    clearCache()
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala:100]: no need to call this if you are not using caching index manager (after the below comment is applied).

File: src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala (hunk 8 above)
Comment (imback82) [reply src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala:108]: now that I look at it one more time, do you need to create `plan1` and `plan2`, or can you just directly use `t1ProjectNode` and `t2ProjectNode`?

File: src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala [hunk 11]
```diff
@@ -78,4 +78,11 @@ trait IndexManager {
    * @param indexName Name of the index to cancel.
    */
   def cancel(indexName: String): Unit
+
+  /**
+   * Get index objects on default index storage location and additional index path
+   *
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala:84]: Can we also add `@param`?

File: src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala [hunk 12]
```diff
@@ -78,4 +78,11 @@ trait IndexManager {
...
+   * @return list of all indexes
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala:85]: `all indexes that match any of the given states`

File: src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala [hunk 13]
```diff
@@ -78,4 +78,11 @@ trait IndexManager {
    * @param indexName Name of the index to cancel.
    */
   def cancel(indexName: String): Unit
+
+  /**
+   * Get index objects on default index storage location and additional index path
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/IndexManager.scala:83]: that match any of the given states?

File: src/test/scala/com/microsoft/hyperspace/index/rules/RuleTestUtils.scala [hunk 14]
```diff
@@ -0,0 +1,83 @@
...
+import org.apache.spark.sql.catalyst.plans.logical.LogicalPlan
+import org.apache.spark.sql.execution.datasources.{FileIndex, HadoopFsRelation}
+import org.apache.spark.sql.execution.datasources.parquet.ParquetFileFormat
+import org.apache.spark.sql.types.{StructField, StructType}
+
+import com.microsoft.hyperspace.actions.Constants
+import com.microsoft.hyperspace.index.{Content, CoveringIndex, Hdfs, IndexConstants, IndexLogEntry, IndexLogManagerImpl, LogicalPlanFingerprint, LogicalPlanSignatureProvider, NoOpFingerprint, Signature, Source, SparkPlan}
+import com.microsoft.hyperspace.index.serde.LogicalPlanSerDeUtils
+
+trait RuleTestUtils {
```
[the remark this answers is not in the document]
Comment (imback82) [reply src/test/scala/com/microsoft/hyperspace/index/rules/RuleTestUtils.scala:31]: Also after #93 is merged, if you extend `HyperspaceSuite`, you don't need to pass around the system path either now.

File: src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala (hunk 8 above)
Comment (imback82) [reply src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala]: Ah ok. You can do `===` instead in that case. But I am fine with either approach.

Comment (sezruby) [reply src/test/scala/com/microsoft/hyperspace/index/rules/RuleUtilsTest.scala]: Thanks for the tip!
