### PR TITLE
Correctly pass HadoopConfiguration to Content.fromDirectory

### LINKED ISSUE #391: Unable to change hyperspace system path to a non-default file system
### Describe the issue

Changing hyperspace location to non-default file system using ```"spark.hyperspace.system.path"``` fails for non-default file systems. This is reprodicible, for example, on a databricks cluster where dbfs is the default file system and user tries to set index root to wasb or abfs

### To Reproduce

1. Databricks cluster (dbfs file system)
2. spark.conf.set("spark.hyperspace.system.path", "wasb:// or abfs://"
3. hs.createIndex(..

```

java.io.IOException: No FileSystem for scheme: wasb
	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2660)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2667)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:94)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2703)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2685)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:373)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
```

### Expected behavior

no error

### RCA
```
val pathStr = "wasb://" + blob + "@" + storageName + ".blob.core.windows.net/hyperspaceIndexes" 
val path = new Path(pathStr)
path.getFileSystem(new Configuration)              >> FAILS WITH THE ABOVE ERROR
path.getFileSystem(spark.sessionState.newHadoopConf())  >> WORKS FINE (also mentioned in this PR #327 
```
This issue happens in https://github.com/microsoft/hyperspace/blob/master/src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala#L197-L199
Need to replace ``` new Configuration``` with ```spark.sessionState.newHadoopConf()``` to make sure spark finds all file systems.

### PR DESCRIPTION
**Pull request by imback82**
Fixes #391.

This PR proposes to fix the issue reported in #391. We missed passing the Hadoop configuration to `Content.fromDirectory` in `CreateActionBase`. This PR removes the default value for the Hadoop configuration in `Content.fromDirectory` since it's error-prone.

### CODE REVIEW

File: src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala [hunk 1]
```diff
@@ -59,6 +59,7 @@ private[actions] abstract class CreateActionBase(dataManager: IndexDataManager)
       indexConfig: IndexConfig,
       path: Path,
       versionId: Int): IndexLogEntry = {
+    val hadoopConf = spark.sessionState.newHadoopConf()
     val absolutePath = PathUtils.makeAbsolute(path, spark.sessionState.newHadoopConf())
```
Comment (apoorvedave1) [inline src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala:63]:
```suggestion
    val absolutePath = PathUtils.makeAbsolute(path, hadoopConf)
```

File: src/main/scala/com/microsoft/hyperspace/actions/OptimizeAction.scala [hunk 2]
```diff
@@ -141,18 +141,16 @@ class OptimizeAction(
...
       properties = previousIndexLogEntry.derivedDataset.properties
         .copy(
-          properties =
-              Hyperspace
-                .getContext(spark)
-                .sourceProviderManager
-                .enrichIndexProperties(
-                  previousIndexLogEntry.relations.head,
-                  prevIndexProperties + (IndexConstants.INDEX_LOG_VERSION -> endId.toString))))
+          properties = Hyperspace
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/actions/OptimizeAction.scala:148]: scalafmt changed this block. Since this PR is small enough, I let this change in.

File: src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala [hunk 3]
```diff
@@ -87,8 +88,8 @@ object Content {
   def fromDirectory(
       path: Path,
       fileIdTracker: FileIdTracker,
+      hadoopConfiguration: Configuration,
       pathFilter: PathFilter = PathUtils.DataPathFilter,
-      hadoopConfiguration: Configuration = new Configuration,
```
Comment (imback82) [inline src/main/scala/com/microsoft/hyperspace/index/IndexLogEntry.scala:91]: Let's just remove the default value since this is error prone.

File: src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTest.scala [hunk 4]
```diff
@@ -286,10 +286,12 @@ class E2EHyperspaceRulesTest extends QueryTest with HyperspaceSuite {
...
-            spark.sql("CREATE TABLE t1 (c1 string, c3 string) USING PARQUET " +
-              s"LOCATION '$nonPartitionedDataPath'")
-            spark.sql("CREATE TABLE t2 (c3 string, c4 int) USING PARQUET " +
-              s"LOCATION '$nonPartitionedDataPath'")
+            spark.sql(
+              "CREATE TABLE t1 (c1 string, c3 string) USING PARQUET " +
+                s"LOCATION '$nonPartitionedDataPath'")
+            spark.sql(
+              "CREATE TABLE t2 (c3 string, c4 int) USING PARQUET " +
+                s"LOCATION '$nonPartitionedDataPath'")
```
Comment (imback82) [inline src/test/scala/com/microsoft/hyperspace/index/E2EHyperspaceRulesTest.scala:294]: Again, scalafmt.

**Review by apoorvedave1 — APPROVED** [review]
one minor comment, but otherwise LGTM 👍 thanks @imback82

File: src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala (hunk 1 above)
Comment (imback82) [reply src/main/scala/com/microsoft/hyperspace/actions/CreateActionBase.scala]: thanks!

**Review by apoorvedave1 — APPROVED** [review]
LGTM, thanks 👍 @imback82

**Comment by sezruby** [comment]
LGTM Thanks!

**Comment by imback82** [comment]
Thanks @apoorvedave1 / @sezruby for the review!
