### PR TITLE
Fix for incorrect explain behavior when df optimized plan has been materialized

### LINKED ISSUE #277: Unexpected behavior of explain api when df is materialized
### Describe the issue

Hyperspace explain api gives incorrect output when the original df is materialized before explain command

### To Reproduce
Note the output: Plan with and without indexes both show index being used.
```scala
  val df = spark.read.option("header", "true").csv(path)

  val hs = new Hyperspace(spark)
  spark.enableHyperspace()

  val df2 = df.filter("c1 = 1")
  println(df2.queryExecution.optimizedPlan) // df2 materialized here. i.e. optimized plan exists by this time.
  hs.explain(df2)
```
Output:
```
=============================================================
Plan with indexes:
=============================================================
Project [c1#10, c2#11]
+- Filter (isnotnull(c1#10) && (cast(c1#10 as int) = 1))
   +- FileScan parquet [c1#10,c2#11] Batched: true, Format: Parquet, Location: InMemoryFileIndex[file:/C:/Users/apdave/github/hyperspace-1/spark-warehouse/indexes/i/v__=0/part-..., PartitionFilters: [], PushedFilters: [IsNotNull(c1)], ReadSchema: struct<c1:string,c2:string>

=============================================================
Plan without indexes:
=============================================================
Project [c1#10, c2#11]
+- Filter (isnotnull(c1#10) && (cast(c1#10 as int) = 1))
   +- FileScan parquet [c1#10,c2#11] Batched: true, Format: Parquet, Location: InMemoryFileIndex[file:/C:/Users/apdave/github/hyperspace-1/spark-warehouse/indexes/i/v__=0/part-..., PartitionFilters: [], PushedFilters: [IsNotNull(c1)], ReadSchema: struct<c1:string,c2:string>

=============================================================
Indexes used:
=============================================================
i:file:/C:/Users/apdave/github/hyperspace-1/spark-warehouse/indexes/i/v__=0

```

### Expected behavior
Note the difference between "Plan with Index" and "Plan without index"
```
=============================================================
Plan with indexes:
=============================================================
Project [c1#10, c2#11]
+- Filter (isnotnull(c1#10) && (cast(c1#10 as int) = 1))
   <----+- FileScan parquet [c1#10,c2#11] Batched: true, Format: Parquet, Location: InMemoryFileIndex[file:/C:/Users/apdave/github/hyperspace-1/spark-warehouse/indexes/i/v__=0/part-..., PartitionFilters: [], PushedFilters: [IsNotNull(c1)], ReadSchema: struct<c1:string,c2:string>---->

=============================================================
Plan without indexes:
=============================================================
Project [c1#10, c2#11]
+- Filter (isnotnull(c1#10) && (cast(c1#10 as int) = 1))
   <----+- FileScan csv [c1#10,c2#11] Batched: false, Format: CSV, Location: InMemoryFileIndex[file:/C:/Users/apdave/github/hyperspace-1/data/1/1], PartitionFilters: [], PushedFilters: [IsNotNull(c1)], ReadSchema: struct<c1:string,c2:string>---->

=============================================================
Indexes used:
=============================================================
i:file:/C:/Users/apdave/github/hyperspace-1/spark-warehouse/indexes/i/v__=0
```

### PR DESCRIPTION
**Pull request by apoorvedave1**
### What is the context for this pull request?
Fixes #277 

 - **Tracking Issue**: #277

### What changes were proposed in this pull request?
Recreate the df on which explain is called. This ensures cleanup of already initialized optimized plans.

### Does this PR introduce _any_ user-facing change?
No

### How was this patch tested?
Unit tests

### CODE REVIEW

File: src/main/scala/org/apache/spark/sql/hyperspace/utils/package.scala [hunk 1]
```diff
@@ -16,12 +16,23 @@
...
   implicit class DataFrameUtils(df: DataFrame) {
     def showString(numRows: Int, truncate: Int, vertical: Boolean = false): String = {
       df.showString(numRows, truncate, vertical)
     }
   }
+
+  // This implementation is picked directly from:
+  // https://github.com/apache/spark/blob/v2.4.4/sql/core/src/main/scala/org/apache/spark/sql/
+  //  Dataset.scala#L76-L80
+  def logicalPlanToDataFrame(sparkSession: SparkSession, logicalPlan: LogicalPlan): DataFrame = {
```
Comment (pirz) [inline src/main/scala/org/apache/spark/sql/hyperspace/utils/package.scala:33]: Just a question:
Is there a reason this is added to the utils and not as a private function in `PlanAnalyzer`?

**Review by pirz — APPROVED** [review]
LGTM, Thanks @apoorvedave1

File: src/main/scala/org/apache/spark/sql/hyperspace/utils/package.scala (hunk 1 above)
Comment (imback82) [inline src/main/scala/org/apache/spark/sql/hyperspace/utils/package.scala:33]: Can you move this to `src/main/scala/org/apache/spark/sql/hyperspace/utils/package.scala` and call `Dataset.ofRows` instead?

Comment (apoorvedave1) [reply src/main/scala/org/apache/spark/sql/hyperspace/utils/package.scala:33]: oh yeah the queries used here are not accessible in PlanAnanlizer because of private[sql] constraint.

File: src/test/scala/com/microsoft/hyperspace/index/plananalysis/ExplainTest.scala [hunk 2]
```diff
@@ -436,6 +436,178 @@ class ExplainTest extends SparkFunSuite with HyperspaceSuite {
...
+      .append(defaultDisplayMode.newLine)
+      .append(defaultDisplayMode.newLine)
+    // scalastyle:on filelinelengthchecker
+
+    val selfJoinDf = df.join(df, df("Col1") === df("Col1"))
+
+    // Materialize the lazily evaluated optimized plan before plan comparison.
+    spark.enableHyperspace()
+    selfJoinDf.queryExecution.optimizedPlan
+    spark.disableHyperspace()
```
Comment (apoorvedave1) [inline src/test/scala/com/microsoft/hyperspace/index/plananalysis/ExplainTest.scala:604]: Note: the test is same as test titled "Testing default display mode" except for these three lines which materialize the optimized plan.
This materialization fails the test with the original code

File: src/main/scala/org/apache/spark/sql/hyperspace/utils/package.scala (hunk 1 above)
Comment (apoorvedave1) [reply src/main/scala/org/apache/spark/sql/hyperspace/utils/package.scala]: done, thanks @imback82

**Review by imback82 — APPROVED** [review]
LGTM, thanks @apoorvedave1!

(I will wait for @sezruby to take a look before merging.)

**Review by sezruby — APPROVED** [review]
LGTM Thanks @apoorvedave1!
